name: Python Unit-Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Code aus dem Repository holen
        uses: actions/checkout@v4

      - name: 2. Python-Umgebung einrichten
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: 3. Abhängigkeiten installieren
        run: pip install pygame # Passt dies an eure Projekt-Bibliotheken an

      - name: 4. Unit-Tests ausführen
        run: python -m unittest

