name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
    
    - name: Run unit tests
      run: |
        python run_tests.py
    
    - name: Test coverage summary
      run: |
        echo "✅ Unit Tests für Pac-Man Projekt erfolgreich!"
        echo "📊 68 Tests ausgeführt nach Arrange-Act-Assert Muster"